##############################################################################
##                 The Calculus of Inductive Constructions                  ##
##                                                                          ##
##                                Projet Coq                                ##
##                                                                          ##
##                     INRIA                        ENS-CNRS                ##
##              Rocquencourt                        Lyon                    ##
##                                                                          ##
##                                  Coq V7                                  ##
##                                                                          ##
##                                                                          ##
##############################################################################

# WARNING
#
# This Makefile has been automagically generated by coq_makefile
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB=`camlp4 -where`
COQSRC=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS=$(OCAMLLIBS) $(COQSRC)
OPT=
COQFLAGS=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC=$(COQBIN)coqc
GALLINA=gallina
COQDOC=coqdoc
CAMLC=ocamlc -c
CAMLOPTC=ocamlopt -c
CAMLLINK=ocamlc
CAMLOPTLINK=ocamlopt
COQDEP=$(COQBIN)coqdep -c
GRAMMARS=grammar.cma
CAMLP4EXTEND=pa_extend.cmo pa_ifdef.cmo q_MLast.cmo
PP=-pp "camlp4o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS=-I .
COQLIBS=-I .

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES=BoolAux.v\
  Extract.v\
  LetP.v\
  Option.v\
  OrderedListEq.v\
  OrderedListEq_ex.v\
  PolyListAux.v\
  addArray.v\
  algoDilemma1.v\
  algoDotriplet.v\
  algoDotriplets.v\
  algoRun.v\
  algoStalmarck.v\
  algoTrace.v\
  complete.v\
  doTriplet.v\
  doTriplets.v\
  equalBefore.v\
  interImplement.v\
  interImplement2.v\
  interImplement2_ex.v\
  interState.v\
  ltState.v\
  makeTriplet.v\
  memoryImplement.v\
  normalize.v\
  rZ.v\
  refl.v\
  restrictState.v\
  sTactic.v\
  stalmarck.v\
  state.v\
  stateDec.v\
  stateExtra.v\
  trace.v\
  triplet.v\
  unionState.v\
  wfArray.v
VOFILES=$(VFILES:.v=.vo)
VIFILES=$(VFILES:.v=.vi)
GFILES=$(VFILES:.v=.g)
HTMLFILES=$(VFILES:.v=.html)
GHTMLFILES=$(VFILES:.v=.g.html)

all: BoolAux.vo\
  Extract.vo\
  LetP.vo\
  Option.vo\
  OrderedListEq.vo\
  OrderedListEq_ex.vo\
  PolyListAux.vo\
  addArray.vo\
  algoDilemma1.vo\
  algoDotriplet.vo\
  algoDotriplets.vo\
  algoRun.vo\
  algoStalmarck.vo\
  algoTrace.vo\
  complete.vo\
  doTriplet.vo\
  doTriplets.vo\
  equalBefore.vo\
  interImplement.vo\
  interImplement2.vo\
  interImplement2_ex.vo\
  interState.vo\
  ltState.vo\
  makeTriplet.vo\
  memoryImplement.vo\
  normalize.vo\
  rZ.vo\
  refl.vo\
  restrictState.vo\
  sTactic.vo\
  stalmarck.vo\
  state.vo\
  stateDec.vo\
  stateExtra.vo\
  trace.vo\
  triplet.vo\
  unionState.vo\
  wfArray.vo\
  staltac.cmo\
  StalTac.vo\
  StalTac_ex.vo\
  extraction\
  test

spec: $(VIFILES)

gallina: $(GFILES)

html: $(HTMLFILES)

gallinahtml: $(GHTMLFILES)

all.ps: $(VFILES)
	$(COQDOC) -ps -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -ps -g -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



###################
#                 #
# Custom targets. #
#                 #
###################

StalTac.vo: 
	$(COQC) -q -byte StalTac.v

StalTac_ex.vo: 
	$(COQC) -vm -q -byte StalTac_ex.v

test: 
	@echo '***** test: checking the tautology ztwaalf1_be *****'
	extraction/stalmarck 1 extraction/ztwaalf1_be
	@echo '******************** End of test ***********************'

###################
#                 #
# Subdirectories. #
#                 #
###################

extraction:
	cd extraction ; $(MAKE) all

####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html extraction

.SUFFIXES: .mli .ml .cmo .cmi .cmx .v .vo .vi .g .html .tex .g.tex .g.html

.mli.cmi:
	$(CAMLC) $(ZDEBUG) $(ZFLAGS) $<

.ml.cmo:
	$(CAMLC) $(ZDEBUG) $(ZFLAGS) $(PP) $<

.ml.cmx:
	$(CAMLOPTC) $(ZDEBUG) $(ZFLAGS) $(PP) $<

.v.vo:
	$(COQC) $(COQDEBUG) $(COQFLAGS) $*

.v.vi:
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

.v.g:
	$(GALLINA) $<

.v.tex:
	$(COQDOC) -latex $< -o $@

.v.html:
	$(COQDOC) -html $< -o $@

.v.g.tex:
	$(COQDOC) -latex -g $< -o $@

.v.g.html:
	$(COQDOC) -html -g $< -o $@

byte:
	$(MAKE) all "OPT="

opt:
	$(MAKE) all "OPT=-opt"

include .depend

.depend depend:
	rm -f .depend
	$(COQDEP) -i $(COQLIBS) *.v *.ml *.mli >.depend
	$(COQDEP) $(COQLIBS) -suffix .html *.v >>.depend
	(cd extraction ; $(MAKE) depend)

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f *.vo `$(COQC) -where`/user-contrib
	cp -f *.cmo `$(COQC) -where`/user-contrib
	(cd extraction ; $(MAKE) install)

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile

	(cd extraction ; $(MAKE) Makefile)

clean:
	rm -f *.cmo *.cmi *.cmx *.o *.vo *.vi *.g *~
	rm -f all.ps all-gal.ps $(HTMLFILES) $(GHTMLFILES)
	(cd extraction ; $(MAKE) clean)

archclean:
	rm -f *.cmx *.o
	(cd extraction ; $(MAKE) archclean)

html:
	(cd extraction ; $(MAKE) html)

# WARNING
#
# This Makefile has been automagically generated by coq_makefile
# Edit at your own risks !
#
# END OF WARNING

