name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          custom_script: |
            {{before_install}}
            startGroup "Build stalmarck dependencies"
              opam pin add -n -y -k path coq-stalmarck .
              opam update -y
              opam install -y -j 2 coq-stalmarck --deps-only
            endGroup
            startGroup "Build stalmarck"
              opam install -y -v -j 2 coq-stalmarck
              opam list
            endGroup
            startGroup "Build stalmarck-tactic dependencies"
              opam pin add -n -y -k path coq-stalmarck-tactic .
              opam update -y
              opam install -y -j 2 coq-stalmarck-tactic --deps-only
            endGroup
            startGroup "Build stalmarck-tactic"
              opam install -y -v -j 2 coq-stalmarck-tactic
              opam list
            endGroup
            startGroup "Uninstallation test"
              opam remove -y coq-stalmarck-tactic
              opam remove -y coq-stalmarck
            endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
